/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JNIMain */

#ifndef _Included_JNIMain
#define _Included_JNIMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIMain
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIMain_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     JNIMain
 * Method:    getStringFromC2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIMain_getStringFromC2
  (JNIEnv *, jobject);


JNIEXPORT jstring JNICALL Java_JNIMain_accessField
(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_JNIMain_accdssIntStaticField
(JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_JNIMain_accessMethod
(JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_JNIMain_accessStaticMethod
(JNIEnv *, jobject);

JNIEXPORT jobject JNICALL Java_JNIMain_accessConstructor
(JNIEnv *, jobject);

JNIEXPORT jobject JNICALL Java_JNIMain_chineseChar
(JNIEnv *, jobject,jstring);
JNIEXPORT void JNICALL Java_JNIMain_giveArray
(JNIEnv *, jobject, jintArray);

JNIEXPORT jobjectArray JNICALL Java_JNIMain_initStringArray
(JNIEnv *, jobject, jint);

JNIEXPORT jobjectArray JNICALL Java_JNIMain_localRef
(JNIEnv *, jobject);

JNIEXPORT jobjectArray JNICALL Java_JNIMain_createGlobalRef
(JNIEnv *env, jobject jobj);

JNIEXPORT jobjectArray JNICALL Java_JNIMain_getGlobalRef
(JNIEnv *env, jobject jobj);

JNIEXPORT jobjectArray JNICALL Java_JNIMain_delectGlobalRef
(JNIEnv *env, jobject jobj);
#ifdef __cplusplus
}
#endif
#endif
